### ISSUE TITLE
API List是否能够增加request报文透传

### ISSUE THREAD

**Issue by hjjoe1213123** [buaazp/zimg#102]
lua脚本很强大，但是用户身份校验是个问题，如果能将request报文透传过来丢给lua进行用户身份校验就好了，毕竟现在是谁都可以上传图片这点不利于安全，就像这个
http://demo.buaa.us/cc5851a9d5bbf31ab3e245079ec0fed0

**Comment by buaazp** [comment]
refer to #34

**Comment by hjjoe1213123** [comment]
主要是想通过nginx+lua脚本来验证用户，如果采用先上传到临时目录然后再上传到zimg这种方式很浪费时间，用户得到响应就很慢了，如果能透传给lua那么就能先校验好用户之后决定是否继续上传到zimg
