### ISSUE TITLE
Support AutoOrientImage

### ISSUE THREAD

**Issue by hjjoe1213123** [buaazp/zimg#104]
Android手机浏览器Bug导致使用二进制方式上传的时候报文头有图片信息，但是报文体是空的导致zimg无法处理，但是用from表单方式又没法得到json，所以能不能增加表单post上传时也返回json

**Comment by buaazp** [comment]
不能，表单就是为了方便浏览器用户上传，raw-post就是为了程序调用。

你可以自己解析一下表单上传返回的html，那个里面也有md5字段；甚至你都可以不用管返回的字段是什么，自己本地算一下md5值就行了。

**Comment by hjjoe1213123** [comment]
又发现IOS的一个傻逼问题了，拍照的时候竖着拍的，采用二进制上传这张图片后居然是横着的了，不晓得有什么办法来校验这个图片正反没

**Comment by buaazp** [comment]
GetImageOrientation() 获取图片的方向值，然后根据相应的规则旋转图片。

**Comment by hjjoe1213123** [comment]
是指在lua脚本里面还是要修改你的zimg进行处理？

**Comment by buaazp** [comment]
lua脚本API有限，这个只能在zimg里实现。

**Comment by hjjoe1213123** [comment]
以后能加上Request API不？

**Comment by buaazp** [comment]
并没有这个计划。

**Comment by buaazp** [comment]
auto-orientation已经实现：
https://github.com/buaazp/zimg/commit/b069e1b7b2a39abcd52b2a2c268e517c90a42ac2
