### ISSUE TITLE
zimg 能不能用GraphicsMagick 做图片处理

### ISSUE THREAD

**Issue by wanglixiang90** [buaazp/zimg#106]
zimg 能不能用GraphicsMagick 做图片处理，ImageMagick功能强大，但是实时效率和系统兼容性 不如 GraphicsMagick ，zimg 能否增加对 GraphicsMagick 的支持？

**Comment by wanglixiang90** [comment]
对于zimg 访问权限限制的一个想法，上传用网页权限进行上传控制，下载读取用一种key/value 权限限制，不过key/value是由服务器产生的 一组 UUID（类似于！UUID ! UUID,用！ 分割这对KEY/ VALUE 值），zimg服务器端 比对 这组UUID，相同则准许一段访问时间区间，不同直接拒绝访问。

**Comment by buaazp** [comment]
GraphicsMagick并没有比im快，而且也没有im好用。很早之前就切换成gm测试过，渣得很，不信你可以自己换API试试。

**Comment by buaazp** [comment]
不同主题的问题别放在一个issue里讨论，后面人看不清说什么了。

关于权限的问题，我有自己的想法，你提出的东西，你可以自己去把它实现了，然后发PR给我，如果好用，我会合并进主干代码。

**Comment by buaazp** [comment]
refer to #70
