### ISSUE TITLE
zimg服务稳定性问题

### ISSUE THREAD

**Issue by qq528** [buaazp/zimg#112]
发现在使用过程中，只要有一个请求出现异常的时候，整个服务就出现异常了。例如我测试访问了下：http://demo.buaa.us/5f189d8ec57f5a5a0d3dcba47fa797e2?p=3&w=3022220&h=32222200，就导致作者提供的demo服务直接挂掉了（这边跟作者说声对不起哈）。假设服务中有个图片地址会导致服务崩溃，自动重启估计也无效。。。

**Comment by buaazp** [comment]
已修复，配置文件里设置`disable_zoom_up = 1`之后就可避免这种恶意请求。
