### ISSUE TITLE
使用过程中，提几个建议

### ISSUE THREAD

**Issue by qq528** [buaazp/zimg#116]
1、由于zimg访问是用图片md5作为路径，代码处理中为地址开辟了512的空间，但是如果地址超出512的长度，则会引起服务崩溃，所以加上地址长度的判断，超出长度goto forbidden;
2、由于zimg如果允许用户通过参数w等进行图片处理的请求，为了防止恶意参数，可以在配置文件setting中增加max_width,max_height等参数限制最大允许的图片宽度和高度，接收请求的时候对参数进行验证即可；
3、本人创建了一个专门用于zimg讨论的qq群，欢迎大家一起讨论，让zimg更加稳定，发展的更好。谢谢。qq群号：473765712 。点击链接加入群【zimg讨论群】：http://jq.qq.com/?_wv=1027&k=eHd3Gc

**Comment by buaazp** [comment]
1. 大部分浏览器和客户端会限制URL的长度，如果是恶意请求的话确实可能导致一些问题，不过其实很难构造这样大的请求。这个问题确实没考虑到，可以加一个服务端限制。
2. 配置文件里禁用放大选项就行了。
3. 我都不怎么用QQ，以后如果有特别强烈的讨论需求再搞吧。
