### ISSUE TITLE
关于返回结果

### ISSUE THREAD

**Issue by longzhiyou** [buaazp/zimg#120]
建议全部返回json格式数据，对于html格式，一般在实际的工程中是没有多少意义的，我准备试着看一下源码进行修改，不知道能否提交。

**Comment by buaazp** [comment]
暂时不用修改，下个大版本的API会完全符合RESTful的要求，已经在进行中了。

**Comment by Mignet** [comment]
我当前fork的版本已经修改过了，使用的md5，我们确实需要json格式的

**Comment by longzhiyou** [comment]
非常感谢，不知道能否参与此项目的代码开发？

**Comment by buaazp** [comment]
@longzhiyou  下版本是完全重写的，结合了我这两年在实际业务上的很多经验和教训，会去掉不必要的功能，增加更多生产环境需要的东西进来。目前还处于非常初级的阶段，而且混合了很多线上代码，所以不便协同开发，建议等到基本可用的时候再加入进来。

**Comment by qq528** [comment]
非常期待新版本的出来！不知道有没有预计的时间点呢？我这边正在打算用Zimg搭建图床服务。

**Comment by liangjixunz** [comment]
首先非常感谢作者，在理解了整体的思想之后， 现在准备使用zimg做为图片服务器了，由于目前我们公司的图片上传为js和flash的方式，js上传时存在跨域问题，这个一般只要设置响应的headers就可以了，但是我通过zimg.lua设置headers无效（Cache-Control:max-age=7776000,Access-Control-Allow-Origin:*,Access-Control-Allow-Methods:POST）
所以我的解决方式是修改了源码(在返回的时候新增了evhtp_headers_add_header(mp_arg->req->headers_out,evhtp_header_new("Access-Control-Allow-Origin","*",0,0))),很期待作者的下一次改版

**Comment by buaazp** [comment]
@liangjixunz 无效的时候有没有看一下response的header，看你这说法，是不是由于`Access-Control-Allow-Origin`的指是空所以zimg跳过了。

**Comment by liangjixunz** [comment]
@buaazp Access-Control-Allow-Origin:*，上面的少了个*,我是设置了值的

**Comment by buaazp** [comment]
我知道，header的格式是`key:value`，但是你这个header只有key没有value，所以我跳过了，看这儿：

https://github.com/buaazp/zimg/blob/master/src/zhttpd.c#L175

以前没考虑过header的value为空的情况，可以加上。

**Comment by liangjixunz** [comment]
@buaazp 很感谢回复，其实我是填了value的，但是在这里显示不出来 我的value是星号

**Comment by buaazp** [comment]
那是github的转义给你转掉了，我编辑了一下显示出来了。

如果是有值的话，你就得去查一下zimg的response里的header，到底有没有这条：`Access-Control-Allow-Origin:\*`

**Comment by buaazp** [comment]
那是因为github的markdown转义给你转了，我编辑了一下，已经可以显示了。

你配置文件里写错了分隔符，应该用`;`而不是`,`

```
headers             = 'Cache-Control:max-age=7776000;Access-Control-Allow-Origin:*;Access-Control-Allow-Methods:POST'
```

我设置成这样就可以了，不用该源码。

**Comment by liangjixunz** [comment]
@buaazp 我在load_conf方法里面加了日志，证明这个方法根本没执行，所以才会设置无效

**Comment by buaazp** [comment]
@liangjixunz 你自己点开这个地址看看有没有header

http://demo.buaa.us/5f189d8ec57f5a5a0d3dcba47fa797e2

**Comment by liangjixunz** [comment]
@buaazp  问题解决了，是我将返回修改成json后未调用zimg_headers_add方法
