### ISSUE TITLE
404无法访问图片问题

### ISSUE THREAD

**Issue by zzc1984** [buaazp/zimg#125]
Hi，我编译安装完成之前运行zimg服务，可打开默认upload页面，上传一张图片进行测试，显示上传成功，返回一个K值。但是当我点击一方连接的时间就报404 Not found，我是使用默认配置的，查了一下图片文件的确存到了后台服务的bin/img目录下了，请问这是什么原因？
![1](https://cloud.githubusercontent.com/assets/13229798/10474625/5e5cd44c-726b-11e5-88e5-67f66e1a9a98.jpg)

![2](https://cloud.githubusercontent.com/assets/13229798/10474628/663e945c-726b-11e5-80d6-fbc54c6c834d.jpg)

**Comment by buaazp** [comment]
装一下图片解码库，人后重装imagemagick应该可以解决。

看一下相关的issue #88
