### ISSUE TITLE
删除图片接口

### ISSUE THREAD

**Issue by yuanzs** [buaazp/zimg#130]
你好，zimg作者，我想问下，有没有关于删除某个图片的接口。

**Comment by kfeng0806** [comment]
[文档](http://zimg.buaa.us/documents/guidebookcn/)中有写

**Comment by yuanzs** [comment]
还有一个问题，就是上传安全控制，看介绍，这个好像可以随便上传

**Comment by kfeng0806** [comment]
[配置](http://zimg.buaa.us/documents/guidebookcn/)中有写

**Comment by yuanzs** [comment]
如果绑定了IP，下载的时候，用域名配置，需要公网IP，可以做域名映射吗

**Comment by buaazp** [comment]
http://demo.buaa.us/ 像我这个？什么叫域名映射？
我是直接dns配置到服务器的公网IP，服务器上起一个nginx转发到zimg的4869端口，是不是能满足你的需求。

**Comment by yuanzs** [comment]
差不多，就是我要img.more.com这个单独域名访问图片，你的意思，在nginx配置一下，转发到zimg，就可以了，是吗？zimg配置绑定的IP的就是nginx服务器这台ip吗？

**Comment by buaazp** [comment]
绑zimg服务器的IP
