### ISSUE TITLE
GIF默认显示原始图片?

### ISSUE THREAD

**Issue by kfeng0806** [buaazp/zimg#133]
是否能让GIF格式的图片默认显示原始图片 就是添加p=0参数后的效果
因为发现经过imagemagick转换过的gif都会只保留初始帧 但是一般情况下的GIF都是动态帧
所以是否可以默认让GIF格式显示原始文件而不经过imagemagick转换?

**Comment by buaazp** [comment]
默认显示的是转换过的小图片，这是策略，你可以在代码里做相关的转换。
