### ISSUE TITLE
部分PNG格式图片404

### ISSUE THREAD

**Issue by kfeng0806** [buaazp/zimg#135]
有一些用户上传了部分PNG图片 在服务器中经过imagemagick转换会出现错误404
经过测试在作者文档中的接口上传后也是显示404
但是将原图下载下载来在PS中重新保存一次PNG再上传即正常
目测可能是部分PNG图片编码或者是图片经过某些软件压缩过后的问题
是否可以考虑一下在图片转换失败的情况下直接返回原始文件而不返回404错误?

**Comment by buaazp** [comment]
线上服务都会遇到各种各样的损坏图片，以GIF、PNG居多，其实最好的做法是上传时检查，校验图片头部，如果失败则拒绝上传，我们的线上服务、Google photos都是这么搞的。

zimg目前版本还没有上传是检查策略，已经在写了，下个版本发布。

之所以不能打开失败时返回原图，是因为会导致大小和格式不一致。

**Comment by kfeng0806** [comment]
404错误确实是因为直接上传了未经验证的损坏图片造成的 在上传服务接口处添加了校验删除问题图片后
已正常运作

**Comment by buaazp** [comment]
Good
