### ISSUE TITLE
功能建议: 长期无请求图片文件自动清理

### ISSUE THREAD

**Issue by kfeng0806** [buaazp/zimg#137]
使用作者的程序运行了一段时间后发现对于流量较大的网站数据储存量会以爆炸式的形式增长
主要是使用了本地储存模式，每张图都会生成新的文件而且普遍会比原图大一些（90质量）
如果数据量很大的话其中也有可能会存在大量的失效或者上传后未使用的无用图片数据，作者是否会考虑一下增加对于一定时间无请求文件的自动删除的功能呢？

**Comment by buaazp** [comment]
这个在zimg端不好做，业务端统计访问频率或制定过期规则，显示调用zimg的删除接口来实现。

**Comment by kfeng0806** [comment]
如果那样的话图片的访问可能会都需要经过业务端，是否可以在zimg增加一个接口通知选项，每次处理完用户请求后将图片的md5通知给业务端这样就可以实现统计访问频率了。

**Comment by boin** [comment]
无访问缓存文件清理可以简单通过文件的atime来确定。

**Comment by buaazp** [comment]
不好做，这个需求先搁置了。
