### ISSUE TITLE
上传webp格式的图片，传参数p＝0，图片反而变小了

### ISSUE THREAD

**Issue by xiaozhilaoliu** [buaazp/zimg#140]
一张webp格式的图片，上传之后获取展示，传参数p＝0获取图片，获取原图，比不加任何图片，图片变小了。

不理解，原图应该更大点啊

这是一张测试的图片：
http://demo.buaa.us/ec53d62c5743e07371673e5649b1555b

**Comment by buaazp** [comment]
`p=0`的时候，原图是多大就是多大，因为后端没处理。

其他请求下，因为有图片处理和格式转换，体积可能会比原图大。典型的如webp转成默认的jpeg，体积当然会变大。

**Comment by xiaozhilaoliu** [comment]
@buaazp 明白了，如果我不指定格式的话，会采取默认的压缩方式，这样导致变大的
