### ISSUE TITLE
centos下make的时候出现以下错误，help

### ISSUE THREAD

**Issue by Mignet** [buaazp/zimg#143]
/home/zimg/src/zcache.c: In function ‘retry_cache’:
/home/zimg/src/zcache.c:55: error: ‘MEMCACHED_BEHAVIOR_TCP_KEEPALIVE’ undeclared (first use in this function)
/home/zimg/src/zcache.c:55: error: (Each undeclared identifier is reported only once
/home/zimg/src/zcache.c:55: error: for each function it appears in.)
make[3]: *** [CMakeFiles/zimg.dir/zcache.c.o] Error 1
make[3]: Leaving directory `/home/zimg/build/zimg'
make[2]: *** [CMakeFiles/zimg.dir/all] Error 2
make[2]: Leaving directory `/home/zimg/build/zimg'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/zimg/build/zimg'
cp: cannot stat `zimg': No such file or directory

**Comment by Mignet** [comment]
https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz

**Comment by Mignet** [comment]
安装了新版本的libmemcached之后解决了

**Comment by hongjunsu** [comment]
我这边安装了 最新的 libmemcached 也没有用啊1.0.18的
