### ISSUE TITLE
Zimg 怎么导入 c-free 中查看 编译 运行？

### ISSUE THREAD

**Issue by simon-miao** [buaazp/zimg#144]
如题：

谢谢zimg的作者，提供这么好的工具，给大家使用。

**Comment by buaazp** [comment]
c-free是这个吗？http://www.programarts.com/cfree_ch/

zimg不支持windows，只能在*nix下编译，c-free里顶多能看看代码。

**Comment by simon-miao** [comment]
我还想着，在windows下找个 IDE 方便调试，理解代码呢。在Linux下，只能命令行了？

**Comment by buaazp** [comment]
是的，Linux下开发的技术栈建议从基本的开始了解学习一下。
