### ISSUE TITLE
Won't make install

### ISSUE THREAD

**Issue by CartridgeGen** [buaazp/zimg#145]
Hi! I'm trying to compile vapoursynth and requires zimg. Now that i've compiled zimg sucessfully, it won't make install. I've tried redownloading the source and recompiling it with again success but cant install it. I then looked further to see if the makefiles contained the command "install" and none of them do... How can i install zimg for vapoursynth to find it? AND/OR How can i tell vapoursynth where I've compiled it. I've tried different things using the zimg_cflags and zimg_libs but that didin't help to find it.

**Comment by buaazp** [comment]
Do you want to install this vapoursynth: http://www.vapoursynth.com/doc/installation.html

The zimg in its requirements is NOT my zimg...

There are two zimg but you need this one: https://github.com/sekrit-twc/zimg

**Comment by CartridgeGen** [comment]
Ah well thank you! I thought vapoursynth used the real zimg and not some fork. Well bye bye compatibility. For some reason, serkit-twc's zimg, does not run on my ARMHF board.
