### ISSUE TITLE
关于原系统图片迁移，如何将图片迁移到zimg里？

### ISSUE THREAD

**Issue by xiedeying** [buaazp/zimg#146]
有人做过相关的么？

**Comment by buaazp** [comment]
每个人的'原系统'都不同，只能自己写个脚本。你之前存哪儿了？

**Comment by xiedeying** [comment]
就一台linux服务器上 路径结构这样 /home/temp/store/my/jpg/20160415/5mysMS/source.jpg
数据库里再存图片路径这样子 这样可以迁移么？ 需要把store目录下的文件重新存储下，数据库里存的路径重新生成个MD5值？

**Comment by xiedeying** [comment]
因为比较急 原先的方案是nginx+nodejs 在考虑存储扩展时候搜到了zimg 然后没仔细看就汇报了 现在要用zimg做方案。。。

**Comment by liangjixunz** [comment]
@xiedeying 一定要把图片迁移过来？还有你是要用zimg的什么存储方案确定了没有,你扩展的目标是什么样也没说，你让buaazp怎么回答你

**Comment by buaazp** [comment]
不必着急，静下来仔细想一想，肯定是可以迁移的，如果使用zimg的本地存储模式脚本也是很容易写的。
