### ISSUE TITLE
图片压缩

### ISSUE THREAD

**Issue by caiwangjue** [buaazp/zimg#147]
通过zimg上传后的图片，设置quality=10，保存的图片和原图大小没什么区别，能否设置保存的图片根据quality来压缩?

**Comment by buaazp** [comment]
上传的时候进行压缩？这个是一个新的需求，我们产品上的策略是上传的时候保存原图一份，压缩好的1080p一份，这个功能会在下个大版本中放出来。

目前建议先传一份原图，然后用get接口下载个压缩图，然后把压缩图再上传一遍来曲线救国。
