### ISSUE TITLE
zimg 截图地址rewrite一下可以么？

### ISSUE THREAD

**Issue by xiedeying** [buaazp/zimg#148]
http://demo.buaa.us/5f189d8ec57f5a5a0d3dcba47fa797e2?w=500&h=500&g=1&x=0&y=0&r=45&q=75&f=jpeg 
可以变成 http://demo.buaa.us/5f189d8ec57f5a5a0d3dcba47fa797e2+w=500_h=500_g=1_x=0_y=0_r=45_q=75_f=jpeg 
的形式

**Comment by udng** [comment]
可以的 直接使用nginx重写地址 然后反向代理到zimg即可

**Comment by buaazp** [comment]
楼上正解，nginx里写个rewrite规则即可~
