### ISSUE TITLE
关于最近的imagemagick的严重BUG怎么看...

### ISSUE THREAD

**Issue by kfeng0806** [buaazp/zimg#149]
最近爆出的imagemagick会导致携带上传恶意代码图片可以执行任何指令的严重漏洞
继续使用imagemagick会有问题吗?

**Comment by buaazp** [comment]
开源软件有bug还算正常吧，想想openssl，比imagick用的广多了。imagick虽然代码很恶心，相对来说出漏洞的频率还是比较低的，也无需那么担心，大厂里用的也很多，出漏洞第一时间修复就行了。

而且，关键是没得选啊。。。不用它真没啥可用的。
