### ISSUE TITLE
数据迁移问题

### ISSUE THREAD

**Issue by backkoms** [buaazp/zimg#151]
请指教：

1. 旧有系统有大量图片，十G上百G的量，如果要迁移到zimg有没有什么好办法？

2. 同样的，zimg里的图片迁移出来的方法又是怎样的呢？

**Comment by buaazp** [comment]
关键是你的旧图片是怎么存储的，文件名是什么规则，这些每个人都不一样，没法做出统一的迁移脚本。最好是自己根据自己的已有文件存储规则写个脚本，一个一个post到zimg里面再把返回的key存进数据库。

**Comment by backkoms** [comment]
多谢回复。

看来如果是从zimg迁移出来的话，也是从库里拿到所有key，然后去一个一个下载了。

**Comment by buaazp** [comment]
最保险的是一个一个下载。如果使用本地存储的话，其实也可以遍历zimg的img文件夹，通过文件夹里的数据也可以快速导出。

**Comment by kenneth** [comment]
@buaazp 这个key有没有规律，能否直接计算得到，还是只能等zimg返回这个md5值？

**Comment by buaazp** [comment]
目前版本的key就是文件的md5，可以自己本地算一下。
