### ISSUE TITLE
执行make：错误：libmemcached/memcached.h：没有那个文件或目录

### ISSUE THREAD

**Issue by Jimjipeng** [buaazp/zimg#153]
[  5%] Building C object CMakeFiles/zimg.dir/zscale.c.o
在包含自 /opt/xjp-zimg/work/zimg/src/zlog.h：25 的文件中，
                 从 /opt/xjp-zimg/work/zimg/src/zscale.c：27:
/opt/xjp-zimg/work/zimg/src/zcommon.h:28:36: 错误：libmemcached/memcached.h：没有那个文件或目录
In file included from /opt/xjp-zimg/work/zimg/src/zlog.h:25,
                 from /opt/xjp-zimg/work/zimg/src/zscale.c:27:
/opt/xjp-zimg/work/zimg/src/zcommon.h:48: 错误：expected specifier-qualifier-list before ‘memcached_st’
make[3]: *** [CMakeFiles/zimg.dir/zscale.c.o] 错误 1
make[3]: Leaving directory `/opt/xjp-zimg/work/zimg/build/zimg'
make[2]: *** [CMakeFiles/zimg.dir/all] 错误 2
make[2]: Leaving directory `/opt/xjp-zimg/work/zimg/build/zimg'
make[1]: *** [all] 错误 2
make[1]: Leaving directory `/opt/xjp-zimg/work/zimg/build/zimg'
cp: 无法获取"zimg" 的文件状态(stat): 没有那个文件或目录
make: *** [all] 错误 1

**Comment by buaazp** [comment]
没有装libmemcached-dev吧

**Comment by Jimjipeng** [comment]
我的是CentOS6.4系统，安装了libmemcached-1.0.18，上面错误不知道是意思...
