### ISSUE TITLE
那个文件夹生成规则是什么？

### ISSUE THREAD

**Issue by CCLooMi** [buaazp/zimg#155]
那个文件夹生成规则是什么？我想自己上传文件然后用zimg进行访问

**Comment by szpapas** [comment]
有说明的，hash值的  1-3 位，16进制数 /4, 4-6 位 16进制数 /4

**Comment by buaazp** [comment]
是的，就是简单的md5前六位转成数字再除以4，最早第一版的时候我写的介绍文章里有说明为什么这样做。

http://zimg.buaa.us/documents/Architecture_Design_of_Image_Server/#代码层面

**Comment by yujianhui1993** [comment]
能否自己自定义 文件夹呢 @buaazp
