### ISSUE TITLE
centos 6.5 make 报错

### ISSUE THREAD

**Issue by lilisheng** [buaazp/zimg#156]
-- Found Libmemcached: /usr/lib64/libmemcached.so  
-- Found ImageMagick: /usr/lib64/libMagickCore.so (found version "6.7.2-7") 
-- Found ImageMagick: /usr/lib64/libMagickWand.so (found version "6.7.2-7") 
Diabling SSL
Build Type: Release
Std CFLAGS:  -Wall -fno-strict-aliasing -DPROJECT_VERSION="3.1.0" -D_BSD_SOURCE -D_POSIX_C_SOURCE=200112 -DEVHTP_DISABLE_SSL -std=c99 -Wno-unused-function -Wno-deprecated -DMAGICKCORE_HDRI_ENABLE -DMAGICKCORE_QUANTUM_DEPTH=8
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBEVENT_PTHREADS_LIBRARY (ADVANCED)
    linked by target "zimg" in directory /opt/zimg/src

-- Configuring incomplete, errors occurred!
See also "/opt/zimg/build/zimg/CMakeFiles/CMakeOutput.log".
make[1]: Entering directory `/opt/zimg/build/zimg'
make[1]: *** 没有指明目标并且找不到 makefile。 停止。
make[1]: Leaving directory `/opt/zimg/build/zimg'
cp: 无法获取"zimg" 的文件状态(stat): 没有那个文件或目录
make: *** [all] 错误 1

**Comment by yzx226** [comment]
在CentOS7安装过程中遇到了类似的问题，分析了一下，应该是缺少编译器
sudo yum install gcc-c++
安装后gcc-c++后，把原来整个zimg目录删除了，重新git，再来一遍就好了
