### ISSUE TITLE
zimg make失败

### ISSUE THREAD

**Issue by sljacksun** [buaazp/zimg#159]
mkdir -p build/zimg
cd build/zimg; cmake /home/sunlei/zimg/src; make; cp zimg /home/sunlei/zimg/bin
CMake Error at /usr/local/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find ImageMagick (missing: ImageMagick_MagickCore_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.0/Modules/FindImageMagick.cmake:234 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:70 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/sunlei/zimg/build/zimg/CMakeFiles/CMakeOutput.log".
make[1]: Entering directory `/home/sunlei/zimg/build/zimg'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/home/sunlei/zimg/build/zimg'
cp: cannot stat ?.img?. No such file or directory
make: *** [all] Error 1

**Comment by hand-code** [comment]
Could NOT find ImageMagick

**Comment by buaazp** [comment]
恩，没装libmagickwand开发库
