### ISSUE TITLE
zimg.lua load failed 问题

### ISSUE THREAD

**Issue by linjunnan** [buaazp/zimg#168]
启动zimg遇到提示lua配置文件加载失败。
    if(load_conf(conf_file) == -1)
    {
        fprintf(stderr, "'%s' load failed!\n", conf_file);
        return -1;
    }

static int load_conf(const char *conf)
{
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    if (luaL_loadfile(L, conf) || lua_pcall(L, 0, 0, 0))
    {
        lua_close(L);
        return -1;
    }
应该是这里出错，请问要怎么解决这个问题？

**Comment by buaazp** [comment]
启动命令和错误提示贴一下，如果自己改了配置文件的话，最好用默认的试试，改过不符合lua语法的话会解析失败。

**Comment by linjunnan** [comment]
嗯，已经找到是配置语法有误，注释习惯了用#，。。没仔细检查就提了，抱歉！
