### ISSUE TITLE
求助：关于图片的exif中Orientation属性

### ISSUE THREAD

**Issue by toeasy** [buaazp/zimg#177]
现象：我们在iOS中使用相机拍照上传后会旋转90度，这也是iOS普遍的问题
处理方法也简单：根据exif的Orientation属性判断，Orientation有几个值代表是旋转多少度；
问题：zimg中好像把Orientation值固定更改为1了，
        代码在https://github.com/buaazp/zimg/blob/master/src/zscale.c#L202
不知道有没有办法保留Orientation的原值

**Comment by buaazp** [comment]
这是个bug，我尽快修复。

关于orientation的处理方法，一般是做一个自动的修正，修正完之后会把这个字段置为0。这样你下载的时候就不用操心方向的问题。这种处理方法如何？

**Comment by toeasy** [comment]
经我们测试观察，所有的图片上传zimg后，orientation值都为1，所以下载后也是1，也就无法利用orientation进行判断方向了。
您说的自动修正是如何实现呢？

**Comment by buaazp** [comment]
这儿有bug，设计意图是，下载的时候会进行方向修正。但是当时只是改了一下exif里的字段没有做实际的修正。刚刚已经提交，你拉一下代码重新试试：

https://github.com/buaazp/zimg/commit/b069e1b7b2a39abcd52b2a2c268e517c90a42ac2

**Comment by toeasy** [comment]
感谢！
