### ISSUE TITLE
zimg make error 

### ISSUE THREAD

**Issue by hongjunsu** [buaazp/zimg#178]
/usr/zimg/src/main.c: 在函数‘init_thread’中:
/usr/zimg/src/main.c:418: 错误：‘MEMCACHED_BEHAVIOR_TCP_KEEPALIVE’未声明(在此函数内第一次使用)
/usr/zimg/src/main.c:418: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
/usr/zimg/src/main.c:418: 错误：所在的函数内也只报告一次。)
/usr/zimg/src/main.c: 在函数‘main’中:
/usr/zimg/src/main.c:603: 错误：‘MEMCACHED_BEHAVIOR_TCP_KEEPALIVE’未声明(在此函数内第一次使用)

please give some advice

**Comment by buaazp** [comment]
系统自带的libmemcached版本过低
