### ISSUE TITLE
进入到目录执行 make的时候报错

### ISSUE THREAD

**Issue by justein** [buaazp/zimg#183]
大概看了一下MakeFile，前面已经自己安装过libjpeg-turbo这些了，怎么deps里还要再来一遍？

**Comment by siusn** [comment]
遇到了同样的问题

**Comment by buaazp** [comment]
最新的代码依靠自己的 deps 的第三方库，避免许多人自己编译依赖出问题，版本不对等问题。

只是网站里的文档没有更新。

**Comment by justein** [comment]
已经成功编译，谢谢回复
