### ISSUE TITLE
图片分类存储的问题

### ISSUE THREAD

**Issue by BeaverCC** [buaazp/zimg#191]
你好，我们在使用zimg做图片存储，现在有个需求是在上传的时候指定个分类，或者类似打tag的操作。方便我们后面对某一个分类的图片做导出迁移等操作。

请问下，zimg是否支持这个功能。

**Comment by buaazp** [comment]
自定义元信息的存储比较复杂，需要重新设计，建议在自己的数据库里存储，既方便又可靠，zimg当做对象存储来用。

**Comment by BeaverCC** [comment]
好的，那我们考虑下其他方案
