### ISSUE TITLE
zimg图片是否有做下载限制？

### ISSUE THREAD

**Issue by xiaodongning** [buaazp/zimg#192]
现在有需要把zimg的图片导出，从数据库取出图片名让后循环一张张下。到是下载到到某一张就请求超时。但是通过浏览器访问是正常的。 下载程序用php和c#跑了都一样，第一次下到100张左右就超时，有时下了几张就超时。zimg部署在阿里云服务器上

**Comment by buaazp** [comment]
超时这个错误太模糊了，下载失败的时候能看一下服务器端的日志吗？是不是服务挂了还是出错了。

**Comment by xiaodongning** [comment]
我看了下日志里面也没报错，服务器是正常的，图片能正常访问。超时是C# try catch 抛出的，我用php在控制台跑并没有报错，只是一直不动。zimg是不是有对 这种频繁访问做限制呢？

**Comment by buaazp** [comment]
没有做特殊的限制，你试单线程一个接着一个图片下载吗？可以在卡住的时候看一下CPU占用，是不是zimg进程占用的资源很高？我怀疑是你用默认的下载路径来下载，实际上zimg在做图片压缩，遇到某些图片比较复杂，会占用大量CPU导致超时。建议换成下载URL加上`?p=0`参数，会直接下载原图而不进行图片压缩，看看还有没有问题。

**Comment by xiaodongning** [comment]
好的，谢了！我也觉得有可能是这原因。为保证图片质量我是用?p=0参数。
