### ISSUE TITLE
zimg/src/zdb.c:23:10: fatal error: 'wand/magick_wand.h' file not found

### ISSUE THREAD

**Issue by wuyachao** [buaazp/zimg#198]
你好，我在mac环境下按照文档安装，make的时候报错找不到这个文件。搜了一下相关问题，但是我找不到这个文件，请问这个wand/magick_wand.h在哪里呢？该如何修改呢

**Comment by wuyachao** [comment]
我使用brew安装的imagemagick版本是7.0.6-7

**Comment by wuyachao** [comment]
已经解决，ImageMagick-7貌似没有 wand这个目录，安装ImageMagick-6。
还是没找到，执行`export C_INCLUDE_PATH=/usr/local/include/ImageMagick-6`就好了

**Comment by buaazp** [comment]
对的，目前没有兼容 imagemagick 7，改动比较大。

**Comment by jjeejj** [comment]
@buaazp  现在还是没有兼容  imagemagick 7吗？，我也是mac 机器，安装的时候也是报的这个错误
 fatal error: 'wand/magick_wand.h' file not found  #include <wand/magick_wand.h>
