### ISSUE TITLE
请问图片的key的命名规则是什么？

### ISSUE THREAD

**Issue by wuyachao** [buaazp/zimg#200]
1.上传图片之后生成一个md5：`7fc5862e4f08497b51b4071f453e1bb6`
2.默认请求如：`www.xxx.com/7fc5862e4f08497b51b4071f453e1bb6`,得到的存储的key为`7fc5862e4f08497b51b4071f453e1bb6:0:0:1:0:-1:-1:0:75:jpeg`
3.倾斜45度角：`www.xxx.com/7fc5862e4f08497b51b4071f453e1bb6?r=45`后，得到的key为
`7fc5862e4f08497b51b4071f453e1bb6:0:0:1:0:-1:-1:45:75:jpeg`

----分割线----
问题：
最后一个是质量，倒数第二个是倾斜的角度，请问各位大佬，这命名规则是什么？不然就只能一个一个尝试了。

**Comment by buaazp** [comment]
这儿就是命名的格式：https://github.com/buaazp/zimg/blob/master/src/zimg.c#L241

**Comment by wuyachao** [comment]
@buaazp 谢谢你
