### ISSUE TITLE
上传多张图片后，返回的md5顺序？

### ISSUE THREAD

**Issue by callELPSYCONGROO** [buaazp/zimg#210]
使用表单提交多张图片到zimg中，action=_/upload_，图片input.name=**img1**、**img2**等等以此类推。
返回给我的是一个html。
那么html中所展示的md5值的顺序，与我上传图片时的input.name有关吗？还是说与其他相关？

**Comment by buaazp** [comment]
是表单里的文件顺序

**Comment by callELPSYCONGROO** [comment]
嗯，谢谢啦~
