### ISSUE TITLE
在alpine:3.7编译安装zimg报错

### ISSUE THREAD

**Issue by wangyp0701** [buaazp/zimg#218]
![image](https://user-images.githubusercontent.com/33682005/41144463-98f95188-6b2f-11e8-8ac3-962612b08ac0.png)
Std CFLAGS:  -Wall -fno-strict-aliasing -DPROJECT_VERSION="3.2.0" -D_BSD_SOURCE -D_POSIX_C_SOURCE=200112 -std=c99 -Wno-unused-function -Wno-deprecated -DMAGICKCORE_HDRI_ENABLE -DMAGICKCORE_QUANTUM_DEPTH=8
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/zimg/build/zimg
make[1]: Entering directory '/tmp/zimg/build/zimg'
make[2]: Entering directory '/tmp/zimg/build/zimg'
make[3]: Entering directory '/tmp/zimg/build/zimg'
Scanning dependencies of target zimg
make[3]: Leaving directory '/tmp/zimg/build/zimg'
make[3]: Entering directory '/tmp/zimg/build/zimg'
[  4%] Building C object CMakeFiles/zimg.dir/main.c.o
[  9%] Building C object CMakeFiles/zimg.dir/zcache.c.o
[ 14%] Building C object CMakeFiles/zimg.dir/zaccess.c.o
[ 19%] Building C object CMakeFiles/zimg.dir/zdb.c.o
In file included from /tmp/zimg/src/zaccess.c:24:0:
/tmp/zimg/src/zaccess.h:40:5: error: unknown type name 'uint'
     uint deny; /* unsigned  deny:1; */
     ^~~~
/tmp/zimg/src/zaccess.h:49:5: error: unknown type name 'uint'
     uint n;
     ^~~~
make[3]: *** [CMakeFiles/zimg.dir/build.make:87: CMakeFiles/zimg.dir/zaccess.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/tmp/zimg/build/zimg'
make[2]: *** [CMakeFiles/Makefile2:68: CMakeFiles/zimg.dir/all] Error 2
make[2]: Leaving directory '/tmp/zimg/build/zimg'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/tmp/zimg/build/zimg'
cp: cannot stat 'zimg': No such file or directory
make: *** [Makefile:23: all] Error 1

**Comment by lcc-321** [comment]
我也遇到了 ... 换成 centos 就没问题 ...
