### ISSUE TITLE
编译zimg时错误

### ISSUE THREAD

**Issue by boxcore** [buaazp/zimg#22]
$ cd zimg
$ sudo make  # then show errors...

```
-- Configuring incomplete, errors occurred!
make[1]: Entering directory `/root/zimg/build/zimg'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/root/zimg/build/zimg'
cp: cannot stat `zimg': No such file or directory
make: *** [all] Error 1
```

**Comment by Carl2016** [comment]
mkdir -p build/zimg
cd build/zimg; cmake /data/zimg/src; make; cp zimg /data/zimg/bin
-- Could NOT find LibEventPthreads (missing:  LIBEVENT_PTHREADS_LIBRARY) 
-- Could NOT find LibEventOpenssl (missing:  LIBEVENT_OPENSSL_LIBRARY) 
-- Found ImageMagick: /usr/lib64/libMagickCore.so (found version "6.7.2-7") 
-- Found ImageMagick: /usr/lib64/libMagickWand.so (found version "6.7.2-7") 
Diabling SSL
Build Type: Release
Std CFLAGS:  -Wall -fno-strict-aliasing -DPROJECT_VERSION="3.1.0" -D_BSD_SOURCE -D_POSIX_C_SOURCE=200112 -DEVHTP_DISABLE_SSL -std=c99 -Wno-unused-function -Wno-deprecated -DMAGICKCORE_HDRI_ENABLE -DMAGICKCORE_QUANTUM_DEPTH=8
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBEVENT_PTHREADS_LIBRARY (ADVANCED)
    linked by target "zimg" in directory /data/zimg/src

-- Configuring incomplete, errors occurred!
See also "/data/zimg/build/zimg/CMakeFiles/CMakeOutput.log".
make[1]: Entering directory `/data/zimg/build/zimg'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/data/zimg/build/zimg'
cp: cannot stat `zimg': No such file or directory
make: *** [all] Error 1

**Comment by buaazp** [comment]
Could NOT find LibEventPthreads
Could NOT find LibEventOpenssl
