### ISSUE TITLE
你好，用php curl上传图片到zimg该如何获取json返回数据？

### ISSUE THREAD

**Issue by lakeui** [buaazp/zimg#45]
我用php curl上传图片成功了，可一直返回html格式，根据文档说的row_post方式，可查询资料php里面没有这个，一直尝试了多次，还是没有成功，特此求解，希望作者能提供几门语言的api上传接口，目前只提供一些curl命令行接口，谢谢

**Comment by heXiangpeng** [comment]
你发的链接是服务器图片传zimg的，怎么传本地图片呢？
