### ISSUE TITLE
to-do feature

### ISSUE THREAD

**Issue by zmoon111** [buaazp/zimg#55]
(1)  supervise run, when crash as  online service;

**Comment by buaazp** [comment]
I used zimg via supervise in my demo server: http://demo.buaa.us/

So there's no problem.

**Comment by szpapas** [comment]
I tried to add zimg to supervise, but zimg exit quickly.  How do you configure the supervisor for zimg?  

Thanks.

**Comment by buaazp** [comment]
Use absolute path in your configs.

supervisor config:
```
[program:zimg]
command=/home/zippo/dev/zimg/bin/zimg /home/zippo/dev/zimg/bin/conf/debug.lua
autorestart=true
user=zippo
```

zimg config:
```
is_daemon           = 0
log_name            = '/home/zippo/dev/zimg/bin/log/zimg.log'
root_path           = '/home/zippo/dev/zimg/bin/www/index.html'
admin_path          = '/home/zippo/dev/zimg/bin/www/admin.html'
script_name         = '/home/zippo/dev/zimg/bin/script/process.lua'
img_path            = '/home/zippo/dev/zimg/bin/img'
```

**Comment by szpapas** [comment]
Thanks.  It still got crash when upload image at the same time.  So I duplicate the zimg.lua with different tcp port. 

das@ubuntu:/etc/supervisor/conf.d$ cat app.conf 
[program:zimg]
command=/opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg.lua
directory=/opt/zimg/bin
autorestart=true
user=root

[program:zimg2]
command=/opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg2.lua
directory=/opt/zimg/bin
autorestart=true
user=root

[program:zimg3]
command=/opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg3.lua
directory=/opt/zimg/bin
autorestart=true
user=root

[program:zimg4]
command=/opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg4.lua
directory=/opt/zimg/bin
autorestart=true
user=root

So I have 4 zimg running on different tcp port.

root@ubuntu:/etc/supervisor/conf.d# ps -ef | grep zimg 
root      1146  1139  0 23:23 ?        00:00:00 /opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg3.lua
root      1147  1139  0 23:23 ?        00:00:00 /opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg2.lua
root      1148  1139  0 23:23 ?        00:00:00 /opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg.lua
root      1149  1139  0 23:23 ?        00:00:00 /opt/zimg/bin/zimg /opt/zimg/bin/conf/zimg4.lua
root      1171  1089  0 23:24 pts/0    00:00:00 grep --color=auto zimg

Nginx for load balance.
