### ISSUE TITLE
能否支持固定图片名称

### ISSUE THREAD

**Issue by littlehui** [buaazp/zimg#58]
您好，zimg上传图片都会产生一个新的url。当用于用户头像存储的时候，外部系统需要链接到这个头像的地址。如果更改了用户头像图片，外部系统无法随之更新，造成一定困扰。能否在下个版本考虑下这种问题呢？比如在上传图片的时候固定一个名称，通过名称也可以访问这个图片，通过md5也可以访问这个图片。

**Comment by buaazp** [comment]
不能，这个太难了。
你前面肯定得有数据库吧，把头像URL作为user表里的一项不就完了么。。。

**Comment by littlehui** [comment]
谢谢 buaazp的回复，因为我们遇到的场景是。系统发送的消息会带上我们的头像，一旦消息发送出去就是头像就是固定的值了。后面的解决方案是在系统里固定了头像的URL，访问zimg的图片过程中先访问系统的获取头像接口，这样做了一次转换，可以解决单个系统问题。后续，考虑部署一个代理应用在zimg服务器上，其他系统需要固话URL通过配置相应接口加入使用。
