### ISSUE TITLE
上传到zimg 后 ，访问新生成的默认处理的图片，有些图片的显示发现向左倾斜了90度，有些图片的位置正常。

### ISSUE THREAD

**Issue by weiliangwei** [buaazp/zimg#59]

**Comment by buaazp** [comment]
真是奇葩的问题。。。。麻烦把这些倾斜的图片上传给我的demo服务器然后告诉我一下md5：
http://demo.buaa.us/

**Comment by wei-hai** [comment]
我也遇到这个问题了，所有的图片都是向左旋转了90度

**Comment by buaazp** [comment]
@wei-hai 能找到具体的原图吗，传到我的demo服务器上我看看？
