### ISSUE TITLE
zimg建议与意见，望采纳

### ISSUE THREAD

**Issue by phpqinsir** [buaazp/zimg#60]
本来想通过邮件方式，转念一想。这种方式不能让所有人知道这么个事儿。

感谢作者提供zimg这么好的开源产品。在初次使用的之后，发现有几个功能还不能满足实际的业务需求。通过阅读历史的 issues 。发现这些个问题也比较明显。现列举出来，希望作者后续版本能考虑改进。

一、图片水印功能
    图片水印可以说是一个非常实用也常用的功能。所以，我大胆猜想，这个功能作者也会在持续版本中实现。那么，既然实现，我觉得应该考虑两个点：
1、水印图片来源。一是来源于内置的图片（通过配置文件中配置）。二是通过上传的图片。比如，某个用户上传的图片，希望以自己的头像作为水印放右下角这样的功能。
2、图片水印位置。位置无非是图片的9个位置了。被打水印的图片通过默认的一串参数生成后的图片再行处理。

二、小文件存储。
    既然可以存储海量的小图片。在实际使用中，我们会把一些小文本。比如商品的图文详情。所以，希望有一个上传文本的功能。直接借助现在的轻量级高并发的架构，且后端又是分片的机制。这点也算是现在我们不想重搞一套系统来实现这个功能的小需求吧。

三、避免滥用图片机制
    zimg通过在参数就可以调整大小、灰度、旋转等操作。并且生成的图片默认是存放于硬盘或缓存之中。那么，遇到恶意用户通过改变这些参数，就会导致硬盘或缓存爆满。那么，必须有一个机制能限定这些操作。

    改进方法：
   1、用缓存这种后端存储介质的时候，提供一个缓存时间。这样利用缓存系统自身的机制清除这些图片。当然，可以设置一个开关决定是否起用这个机制。
   2、要么去掉所有参数这个机制的处理图片。而是自定义参数来处理图片。比如：t=goods，则自动生成800*800大小，质量为75的图片。这样，恶意用户便不通过生成不同尺寸的垃圾图片。

好吧！就这么多。题外话：作者居然跟我同年同月同日生。但求我们长命百岁还能继续撸代码。

谢了！

**Comment by jannson** [comment]
我纯路过,也是打算过来给作者提issue的,看到这个issue也来聊聊:
对于 2、要么去掉所有参数这个机制的处理图片。而是自定义参数来处理图片。比如：t=goods.....
作者提供了lua脚本可以实现你的这个功能

对于上传小文件,有beansdb,也就是作者使用的存储后端,作者就不用再整个轮子了

对于定时删除图片, 暂时木有好办法
对于水印,如果是用户上传的,可以在上传之前打上水印

个人喜欢简单的模式,能独立完成功能.业务相关的功能就自己实现:)

**Comment by phpqinsir** [comment]
@jannson 既然zimg定义为图片存储与处理。那么，水印功能单独放到另外的应用，个人觉得不合理。另外，定时删除图片这个是为了防止热点图片过期之后，很多图片可能很长一段时间都用不到，而又占用空间的行为。尽量保证空间合理利用。

**Comment by buaazp** [comment]
问题一：

水印的问题不是不想做，而是跟zimg的设计意图不相符。我已经多次强调过zimg是无状态的，没有也不会引入类似关系型数据库的东西，所以没法存储互相有关联的的信息，这一点很重要。试想，你的业务里希望水印是用户的头像，那zimg怎么知道这个图片属于哪个用户，又怎么知道这个用户的头像在哪？一个配置文件里如何设置针对每个图片的水印信息？

有人会说，那就通过URL来控制，但是URL的设计规则又是要非常精简的，涉及到定位图片的效率问题，你一个图片的URL因为引入水印成了这样：

```
http://demo.buaa.us/5f189d8ec57f5a5a0d3dcba47fa797e2?watermark=http://demo.buaa.us/5f189d8ec57f5a5a0d3dcba47fa797e2&mode=merge&sign=@回忆专用小马甲&postion=center&color=red&shadow=1
```
看着都麻烦。更要命的是，所有不需要水印的图片，也被迫都要去检查和判断水印信息的各种参数，导致效率降低。一个水印要求的参数，比现在zimg支持的所有参数加起来都要多，很可能导致后端存储里的key长度过长，成本太高。

总结一下，zimg的设计就是要求图片和其他任何信息的耦合度为零，凡是需要关系型数据才能完成的需求，zimg都不做。

问题二：

配置文件里设置你想支持的文件格式，上传成功后用

```
http://demo.buaa.us/5f189d8ec57f5a5a0d3dcba47fa797e2?p=0
```

来获取原文件即可下载。不过没事请别这样用，楼上 @jannson  解释得很清楚了，zimg作为纯存储系统没有任何优势可言。

问题三：

1.定时功能不做，没有任何必要，请求量大的话前面顶CDN就完了，请求量小就关闭存储缩略图，每次都实时生成即可。By the way，现在硬盘这么便宜，生成几百份缩略图又如何，根本用不了多少空间，这个zimg本来就是为了小公司小业务设计的，如果规模到上千台存储服务器的话，请期待zimg2。

2.早就实现了，请详细阅读相关文档。

**Comment by phpqinsir** [comment]
期待新架构。其实，我们的应用只处理图片的情况偏小，读取图片的时候居多。

**Comment by phpqinsir** [comment]
@buaazp 忘记问了。作者说的zimg2是指的是zimg 2.2.0这个版本吗？还是指的是你即将要用golang重写的zimg第二代？

**Comment by buaazp** [comment]
指的是全新的zimg

**Comment by hhservice** [comment]
@buaazp 能否透漏下zimg2 的一点消息，比如时间、架构。

**Comment by buaazp** [comment]
@hhservice need more time and tough work.
