### ISSUE TITLE
webp的问题

### ISSUE THREAD

**Issue by jannson** [buaazp/zimg#61]
http://xxx?f=webp 老是出错. 但是直接使用 convert a.jpg a.webp 是成功的.
平台是centos 包的信息如下:
beansdb  ImageMagick-6.8.9-10 libevent-2.0.21-stable  libmemcached-1.0.18  libmemcached-1.0.18.tar.gz  libwebp-0.4.1  zimg
ubuntu下我也试过,同样不行.

出错的日志是:
2015/01/10 09:39:14:728480 [DEBUG] wi_set_quality(im, 75)
2015/01/10 09:39:14:728506 [DEBUG] wi_set_format(im, webp)
2015/01/10 09:39:14:728819 [DEBUG] zimg Requset Get Image[MD5: e8622bbaecce90f7b9205f6ea5a84a5a] Failed!
2015/01/10 09:39:14:728845 [ERROR] 127.0.0.1 fail pic:e8622bbaecce90f7b9205f6ea5a84a5a w:0 h:0 p:1 g:0 x:-1 y:-1 r:0 q:75 f:webp

ImageMagick-6.8.9-10的编译方法是:
./configure --with-webp=yes

运行 convert -list format|grep webp 结果如下:
     WEBP* rw-   WebP Image Format (libwebp 0.4.1[0203])

个人感觉的问题在         ret = MagickSetImageFormat(im, req->fmt); 这个函数.但不懂为何直接用convert命令成功,但在 zimg里就是转换不成功.

**Comment by buaazp** [comment]
收到，我来跟进一下这个问题。

**Comment by jannson** [comment]
解决了这个问题，但是解决得非常恶心。
我自己写了个这样的代码发现：https://gist.github.com/jannson/9e478aad28ff2d59d04b
链接的时候老是优先选择 /usr/lib64/下的一个低版本的库，但是编译的时候选择的是/usr/local/include下面的库。因为看到编译打印的是 /usr/local/include/xxxmagicxxx，我以为是选择了 /usr/local/lib 下的.so了。

解决办法恶心是因为，我不仅在CMakefiles.txt里强制指定了magic的目录，还在CMakeModules/xxx下也强制指定了目录。现在可以用了。

**Comment by buaazp** [comment]
。。。。。
虽然坎坷，解决了就好，这种情况我这边也不好处理。
