### ISSUE TITLE
一个关于一致性hash的问题

### ISSUE THREAD

**Issue by fifsky** [buaazp/zimg#65]
如果我采用SSDB作为后端存储，twemproxy代理SSDB，刚开始如果有两个节点，图片被平均分布在SSDB里面，假如某一天SSDB满了需要增加节点，这个时候原来两个节点的一些图片必定会被hash到新的节点，但是新的节点显然没有图片内容，因为twemproxy并不会把旧节点的内容搬到新节点，这就需要回源操作，但是图片如何回源，这是个问题，不知道zimg是否有类似的处理机制？

**Comment by buaazp** [comment]
由于zimg本身不保存keys（即zimg不知道后端到底存了那些图片），于是这个问题就演变成了twemproxy拓容的问题，其实不止ssdb，不支持自动sharding的存储系统都有这个问题。

解决方案分两种情况来说，第一种是，你的系统允许部分数据miss，这个就简单了，直接加入2台新的ssdb存储并更新twemproxy配置后重启，结果是以前上传过的部分图片由于reblance而发生miss，导致获取失败，这个时候前端系统可以采取重新上传或者其他容错方案解决，按下不表。

第二种情况，你的系统不容忍数据丢失，那么就需要停机维护，把已有的两台机器数据分别拷贝一份至新的机器上，然后把这四台机器配置到twemproxy里面，重启服务，这个时候原本应该hash到server1上的key，有一半hash到了server2，但是server1和server2的数据是完全一样的，所以读请求不会发生miss。那么另一个问题来了，就是新hash到server2上的这一半keys在server1中没用了，浪费空间，需要清理。

清理的过程就比较复杂了，需要把twemproxy中hash计算的那一部分代码搞出来，针对我们已有的keys（前提是调用zimg的前端系统里保存了全部的key，或者用ssdb支持keys命令来获取全部的key）进行计算，根据匹配结果对应删除。

总的来说，twemproxy的rebalance是一个普遍问题，并非只有zimg会遇到，搜索一下会发现很多讨论这个事情的。zimg目前没能提供自动拓容的功能，是因为这个问题确实有困难，期待老吴能尽快支持ssdb cluster，这样我这边就不用操心了。参考：http://www.ideawu.net/blog/archives/838.html

**Comment by fifsky** [comment]
非常感谢 @buaazp 的回复，解答得非常详细，非常好
