### ISSUE TITLE
上传成功，打开时报404

### ISSUE THREAD

**Issue by wys06521** [buaazp/zimg#67]
安装情况：按照安装说明安装的依赖包，有几个路径已经失效，自己从网上找的包，没有装optional的
配置情况：基本默认配置，只把日志基本改成了debug
上传成功，bin/img下也存在上传的文件
打开图片时报404，debug日志如下
2015/02/05 14:04:09:239196 [DEBUG] ============get_request_cb() DONE!===============
2015/02/05 14:04:09:239239 [INFO] 106.39.122.86 succ root page
2015/02/05 14:04:20:919796 [DEBUG] Method: 2
2015/02/05 14:04:20:919933 [DEBUG] evblen = 47467
2015/02/05 14:04:20:919997 [DEBUG] rmblen = 47467
2015/02/05 14:04:20:920043 [DEBUG] boundary Find. boundary = ----WebKitFormBoundarywtZQreCp5EzH9Bvk
2015/02/05 14:04:20:920088 [DEBUG] boundaryPattern = ------WebKitFormBoundarywtZQreCp5EzH9Bvk, strlen = 40
2015/02/05 14:04:20:920130 [DEBUG] File[博物馆.jpg]
2015/02/05 14:04:20:920166 [DEBUG] fileType[jpg]
2015/02/05 14:04:20:920214 [DEBUG] header_value 52 form-data; name="userfile"; filename="博物馆.jpg
2015/02/05 14:04:20:920252 [DEBUG] header_value 10 image/jpeg
2015/02/05 14:04:20:920383 [DEBUG] Begin to Caculate MD5...
2015/02/05 14:04:20:920528 [DEBUG] md5: eaec878ed10c5649499c127fe196c781
2015/02/05 14:04:20:920568 [DEBUG] save_path: /root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781
2015/02/05 14:04:20:920614 [DEBUG] Path[/root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781] is Not Existed!
2015/02/05 14:04:20:920751 [DEBUG] save_path[/root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781] Create Finish.
2015/02/05 14:04:20:920792 [DEBUG] save_name-->: /root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781/0*0
2015/02/05 14:04:20:920831 [DEBUG] File[/root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781/0*0] is Not Existed!
2015/02/05 14:04:20:920880 [DEBUG] Start to Storage the New Image...
2015/02/05 14:04:20:920991 [DEBUG] Image [/root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781/0*0] Write Successfully!
2015/02/05 14:04:20:921146 [DEBUG] Binary Cache Set Key[eaec878ed10c5649499c127fe196c781] Failed!
2015/02/05 14:04:20:921188 [DEBUG] Cache Result: SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
2015/02/05 14:04:20:921224 [INFO] 106.39.122.86 succ post pic:eaec878ed10c5649499c127fe196c781 size:47276
2015/02/05 14:04:20:921272 [DEBUG] ============post_request_cb() DONE!===============
2015/02/05 14:05:05:268986 [DEBUG] Method: 0
2015/02/05 14:05:05:269106 [DEBUG] Got a GET request for </eaec878ed10c5649499c127fe196c781>
2015/02/05 14:05:05:269139 [DEBUG] md5 of request is <eaec878ed10c5649499c127fe196c781>
2015/02/05 14:05:05:269178 [DEBUG] get_img() start processing zimg request...
2015/02/05 14:05:05:269220 [DEBUG] whole_path: /root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781
2015/02/05 14:05:05:269261 [DEBUG] Path[/root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781] is A Dir.
2015/02/05 14:05:05:269304 [DEBUG] key: eaec878ed10c5649499c127fe196c781:0:0:1:0:-1:-1:0:75:jpeg
2015/02/05 14:05:05:269439 [DEBUG] Cache Conn Failed!
2015/02/05 14:05:05:269482 [DEBUG] Start to Find the Image...
2015/02/05 14:05:05:269521 [DEBUG] 0rig File Path: /root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781/0*0
2015/02/05 14:05:05:269560 [DEBUG] Got the rsp_path: /root/zimg/zimg/bin/img/939/801/eaec878ed10c5649499c127fe196c781/0*0_p1_g0_-1*-1_r0_q75.jpeg
2015/02/05 14:05:05:269674 [DEBUG] Cache Result: SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
2015/02/05 14:05:05:269714 [DEBUG] Not Hit Original Image Cache. Begin to Open it.
2015/02/05 14:05:05:270279 [DEBUG] Open Original Image From Disk Failed! 0 != 1
2015/02/05 14:05:05:270323 [DEBUG] Open Original Image From Disk Failed!
2015/02/05 14:05:05:270369 [DEBUG] zimg Requset Get Image[MD5: eaec878ed10c5649499c127fe196c781] Failed!
2015/02/05 14:05:05:270407 [ERROR] 106.39.122.86 fail pic:eaec878ed10c5649499c127fe196c781 w:0 h:0 p:1 g:0 x:-1 y:-1 r:0 q:75 f:jpeg
2015/02/05 14:05:05:270460 [DEBUG] ============get_request_cb() ERROR!===============

需要改配置吗

**Comment by buaazp** [comment]
先用 [http://localhost:4869/eaec878ed10c5649499c127fe196c781?p=0](http://localhost:4869/eaec878ed10c5649499c127fe196c781?p=0) 访问一下看看能不能出来图片。

如果能的话，怀疑是imagemagick库没装好。

**Comment by wys06521** [comment]
能打开，我再去重新装一下imagemagick

**Comment by wys06521** [comment]
重新装一下imagemagick，正常了，谢谢

**Comment by yajsun** [comment]
遇到同样的问题了，但是imagemagick 是安装成功了：
root@pegdev2cn:~/postimg# convert -version
Version: ImageMagick 6.9.2-0 Q16 x86_64 2015-08-21 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC OpenMP
Delegates (built-in): jpeg webp
但是和lz一样报错：
2015/08/21 17:42:13:737069 [DEBUG] Got a GET request for </e646e61a0e1ba9cda406b04bb207f292>
2015/08/21 17:42:13:737103 [DEBUG] md5 of request is <e646e61a0e1ba9cda406b04bb207f292>
2015/08/21 17:42:13:737133 [DEBUG] get_img() start processing zimg request...
2015/08/21 17:42:13:737163 [DEBUG] whole_path: /root/zimg/bin/img/921/441/e646e61a0e1ba9cda406b04bb207f292
2015/08/21 17:42:13:737195 [DEBUG] Path[/root/zimg/bin/img/921/441/e646e61a0e1ba9cda406b04bb207f292] is A Dir.
2015/08/21 17:42:13:737227 [DEBUG] key: e646e61a0e1ba9cda406b04bb207f292:0:0:1:0:-1:-1:0:100:jpeg
2015/08/21 17:42:13:737368 [DEBUG] Cache Result: SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
2015/08/21 17:42:13:737402 [DEBUG] Start to Find the Image...
2015/08/21 17:42:13:737431 [DEBUG] 0rig File Path: /root/zimg/bin/img/921/441/e646e61a0e1ba9cda406b04bb207f292/0*0
2015/08/21 17:42:13:737459 [DEBUG] Got the rsp_path: /root/zimg/bin/img/921/441/e646e61a0e1ba9cda406b04bb207f292/0*0_p1_g0_-1*-1_r0_q100.jpeg
2015/08/21 17:42:13:737650 [DEBUG] Cache Result: SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
2015/08/21 17:42:13:737683 [DEBUG] Not Hit Original Image Cache. Begin to Open it.
2015/08/21 17:42:13:741111 [DEBUG] Open Original Image From Disk Failed! 0 != 1
2015/08/21 17:42:13:741163 [DEBUG] Open Original Image From Disk Failed!
2015/08/21 17:42:13:741221 [DEBUG] zimg Requset Get Image[MD5: e646e61a0e1ba9cda406b04bb207f292] Failed!
2015/08/21 17:42:13:741253 [ERROR] 10.170.203.214 fail pic:e646e61a0e1ba9cda406b04bb207f292 w:0 h:0 p:1 g:0 x:-1 y:-1 r:0 q:100 f:jpeg
2015/08/21 17:42:13:741306 [DEBUG] ============get_request_cb() ERROR!===============

**Comment by yangjiandong** [comment]
大侠，帮我看看：
```
2015/09/22 12:00:29:278656 [INFO] 192.168.1.109 succ root page
2015/09/22 12:00:38:602686 [INFO] 192.168.1.109 succ post pic:f9b22fccda0ccf77e72d168678366fc8 size:1801891
2015/09/22 12:00:39:888662 [ERROR] 192.168.1.109 fail pic:f9b22fccda0ccf77e72d168678366fc8 w:0 h:0 p:1 g:0 x:-1 y:-1 r:0 q:75 f:jpeg
2015/09/22 12:12:55:872352 [DEBUG] File[/home/ek2/workspace/zimg/bin/script/process.lua] is A File.
2015/09/22 12:12:55:872638 [DEBUG] Path[/home/ek2/workspace/zimg/bin/img] is A Dir.
2015/09/22 12:12:55:872704 [DEBUG] Paths Init Finished.
2015/09/22 12:12:55:874403 [DEBUG] Begin to Start Httpd Server...
2015/09/22 12:12:55:874545 [INFO] zimg started
2015/09/22 12:12:55:878859 [DEBUG] thr_args alloc
2015/09/22 12:12:55:879077 [DEBUG] Memcached Connection Init Finished.
2015/09/22 12:12:55:879254 [DEBUG] luaL_newstate alloc
2015/09/22 12:12:55:880619 [DEBUG] zimg_lua: zimg using lua script.
2015/09/22 12:12:59:364724 [DEBUG] Method: 0
2015/09/22 12:12:59:364889 [DEBUG] Root Request.
2015/09/22 12:12:59:365032 [DEBUG] ============get_request_cb() DONE!===============
2015/09/22 12:12:59:365099 [INFO] 192.168.1.109 succ root page
2015/09/22 12:12:59:498123 [DEBUG] Method: 0
2015/09/22 12:12:59:498318 [DEBUG] favicon.ico Request, Denied.
2015/09/22 12:12:59:498391 [DEBUG] headers: 1
2015/09/22 12:13:01:054259 [DEBUG] Method: 2
2015/09/22 12:13:01:054439 [DEBUG] evblen = 192
2015/09/22 12:13:01:054523 [DEBUG] rmblen = 192
2015/09/22 12:13:01:054884 [DEBUG] boundary Find. boundary = ----WebKitFormBoundaryFDReW3hD8IqQbjSR
2015/09/22 12:13:01:054986 [DEBUG] boundaryPattern = ------WebKitFormBoundaryFDReW3hD8IqQbjSR, strlen = 40
2015/09/22 12:13:01:055066 [DEBUG] File[]
2015/09/22 12:13:01:055124 [DEBUG] FileName [] Has No '.' in It.
2015/09/22 12:13:01:055179 [DEBUG] Get Type of File[] Failed!
2015/09/22 12:13:01:055234 [DEBUG] header_value 39 form-data; name="userfile"; filename="
2015/09/22 12:13:01:055291 [DEBUG] header_value 24 application/octet-stream
2015/09/22 12:13:01:055369 [DEBUG] ============post_request_cb() DONE!===============
2015/09/22 12:13:08:972395 [DEBUG] Method: 2
2015/09/22 12:13:08:972567 [DEBUG] evblen = 192
2015/09/22 12:13:08:972643 [DEBUG] rmblen = 192
2015/09/22 12:13:08:972710 [DEBUG] boundary Find. boundary = ----WebKitFormBoundaryFDReW3hD8IqQbjSR
2015/09/22 12:13:08:972768 [DEBUG] boundaryPattern = ------WebKitFormBoundaryFDReW3hD8IqQbjSR, strlen = 40
2015/09/22 12:13:08:972855 [DEBUG] File[]
2015/09/22 12:13:08:972916 [DEBUG] FileName [] Has No '.' in It.
2015/09/22 12:13:08:972970 [DEBUG] Get Type of File[] Failed!
2015/09/22 12:13:08:973025 [DEBUG] header_value 39 form-data; name="userfile"; filename="
2015/09/22 12:13:08:973081 [DEBUG] header_value 24 application/octet-stream
2015/09/22 12:13:08:973157 [DEBUG] ============post_request_cb() DONE!===============
2015/09/22 12:13:09:281829 [DEBUG] Method: 0
2015/09/22 12:13:09:282011 [DEBUG] favicon.ico Request, Denied.
2015/09/22 12:13:09:282083 [DEBUG] headers: 1
2015/09/22 12:13:12:157306 [DEBUG] Method: 0
2015/09/22 12:13:12:157489 [DEBUG] Root Request.
2015/09/22 12:13:12:157596 [DEBUG] ============get_request_cb() DONE!===============
2015/09/22 12:13:12:157660 [INFO] 192.168.1.109 succ root page
2015/09/22 12:13:20:983258 [DEBUG] Method: 2
```

**Comment by yangjiandong** [comment]
```
2015/09/22 12:13:20:983407 [DEBUG] evblen = 1802081
2015/09/22 12:13:20:987356 [DEBUG] rmblen = 1802081
2015/09/22 12:13:20:987444 [DEBUG] boundary Find. boundary = ----WebKitFormBoundary7UpA7UBnewBGT1Et
2015/09/22 12:13:20:987560 [DEBUG] boundaryPattern = ------WebKitFormBoundary7UpA7UBnewBGT1Et, strlen = 40
2015/09/22 12:13:20:987617 [DEBUG] File[IMG_1431.JPG]
2015/09/22 12:13:20:987662 [DEBUG] fileType[JPG]
2015/09/22 12:13:20:987738 [DEBUG] header_value 51 form-data; name="userfile"; filename="IMG_1431.JPG
2015/09/22 12:13:20:987786 [DEBUG] header_value 10 image/jpeg
2015/09/22 12:13:20:995468 [DEBUG] Begin to Caculate MD5...
2015/09/22 12:13:21:005665 [DEBUG] md5: f9b22fccda0ccf77e72d168678366fc8
2015/09/22 12:13:21:005739 [DEBUG] save_path: /home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8
2015/09/22 12:13:21:005791 [DEBUG] Path[/home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8] is A Dir.
2015/09/22 12:13:21:005835 [DEBUG] save_name-->: /home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8/0*0
2015/09/22 12:13:21:005881 [DEBUG] File[/home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8/0*0] is A File.
2015/09/22 12:13:21:005923 [DEBUG] Check File Exist. Needn't Save.
2015/09/22 12:13:21:005965 [INFO] 192.168.1.109 succ post pic:f9b22fccda0ccf77e72d168678366fc8 size:1801891
2015/09/22 12:13:21:006032 [DEBUG] ============post_request_cb() DONE!===============
2015/09/22 12:13:22:405801 [DEBUG] Method: 0
2015/09/22 12:13:22:405983 [DEBUG] Got a GET request for </f9b22fccda0ccf77e72d168678366fc8>
2015/09/22 12:13:22:406057 [DEBUG] md5 of request is <f9b22fccda0ccf77e72d168678366fc8>
2015/09/22 12:13:22:406117 [DEBUG] get_img() start processing zimg request...
2015/09/22 12:13:22:406177 [DEBUG] whole_path: /home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8
2015/09/22 12:13:22:406318 [DEBUG] Path[/home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8] is A Dir.
2015/09/22 12:13:22:406412 [DEBUG] key: f9b22fccda0ccf77e72d168678366fc8:0:0:1:0:-1:-1:0:75:jpeg
2015/09/22 12:13:22:406817 [DEBUG] Cache Conn Failed!
2015/09/22 12:13:22:406903 [DEBUG] Start to Find the Image...
2015/09/22 12:13:22:406963 [DEBUG] 0rig File Path: /home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8/0*0
2015/09/22 12:13:22:407021 [DEBUG] Got the rsp_path: /home/ek2/workspace/zimg/bin/img/998/139/f9b22fccda0ccf77e72d168678366fc8/0*0_p1_g0_-1*-1_r0_q75.jpeg
2015/09/22 12:13:22:407318 [DEBUG] Cache Result: SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
2015/09/22 12:13:22:407388 [DEBUG] Not Hit Original Image Cache. Begin to Open it.
2015/09/22 12:13:22:416375 [DEBUG] Open Original Image From Disk Failed! 0 != 1
2015/09/22 12:13:22:416487 [DEBUG] Open Original Image From Disk Failed!
2015/09/22 12:13:22:416590 [DEBUG] zimg Requset Get Image[MD5: f9b22fccda0ccf77e72d168678366fc8] Failed!
2015/09/22 12:13:22:416651 [ERROR] 192.168.1.109 fail pic:f9b22fccda0ccf77e72d168678366fc8 w:0 h:0 p:1 g:0 x:-1 y:-1 r:0 q:75 f:jpeg
2015/09/22 12:13:22:416739 [DEBUG] ============get_request_cb() ERROR!===============
```
