### ISSUE TITLE
安卓客户端上传图片如何才能获得json返回值

### ISSUE THREAD

**Issue by nosun** [buaazp/zimg#68]
首先非常感谢zimg这样优秀的作品，最近在一个测试项目中搭建了一个zimg图片服务器用于为安卓客户端上传图片服务，说明文档提到需要用raw-post 方式 服务器才能返回 json体消息，可是我们做客户端的同事做了些尝试始终都返回的是html的返回值，于是只能用正则处理，这个地方比较关键，我看comment中也经常会提到这个问题，是否有改进的计划么，或者有什么其他的办法处理。

**Comment by buaazp** [comment]
Server这边对http raw-post的处理是完全按照HTTP的协议标准来接收的，之所以总是不能用，是因为不同平台的HTTP库不一样。一般的库提供的上传文件的方法都是走`multipart/form`这种方式来上传。目前还不知道你们Android同事用的是哪个http库，最好把其中发post请求的那一段代码贴一下我看看，虽然我不懂JAVA，也可以帮忙查一查。基本上都是用法不对，靠谱的http库应该都会提供raw-post接口的。

**Comment by nosun** [comment]
我用php写了个接口，然后转给了zimg端口，参考了这里一位网友的经验，这样还比较好，前面加php还可以进行验证，感觉更加牢固了。

**Comment by buaazp** [comment]
对，这样的用法其实是蛮好的。
