### ISSUE TITLE
安装成功后，有几点作者亟待解决的问题和建议

### ISSUE THREAD

**Issue by shinebay** [buaazp/zimg#70]
感谢作者开发这么优秀一个工具出来，web运营的福音啊，今晚试用了一下感觉非常不错，有几点问题:
1.作为一张图片，首要问题就是防盗链，这方面我还没看到zimg有任何关于防盗链的描述。
2.前面有外国佬提到了如何给予用户上传的权限?比如只能在用户已登录的情况下才能上传图片到自己个人主页，游客就没有权限，但zimg没有权限验证，如果加上上面所说的不能防盗链，那么任何使用zimg作为image server的网站都可以成为免费图床了，在带宽昂贵的兲朝有点可怕。粗略想了想还是web层服务器和图片zimg服务器共用同一个可逆式加密的token，web服务器存在cookie中，zimg服务器把token存在URL中。
3.上面也有网友说了，每种尺寸都要缓存，那么就会有人恶意输入各种尺寸来生成非常多的垃圾图片，你的回答是几百张图片对于硬盘成本来说太小了，现在假设一个pinterest网站，打开chrome的console，用jQuery遍历每一张图片，假设一个网站有两万张图片，每张图片平均大小600*400，js对每张图片嵌套两个for循环，从1*1一直循环到600*400，请求生成240000图片，而Linux单个文件夹下不能超过2000张图片，显然有违背初衷，而这一切操作都非常简单，仅在chrome的console下完成，如果再循环遍历2万张图片，240000*20000=48亿张垃圾图片，我觉得解决办法还是采用可逆式加密，将参数如截取的长宽高不明文暴露在URL内，而是采用加密后一串值来表示，服务器接收到URL的密文解密后再进行相关缩放啊或是黑白旋转处理。或者干脆用style1.jpg或是style2.jpg来表示，用个config文件把对应的长宽高用数组记录下来就OK了
其余关于加水印和圆角处理等都有人反应了，希望作者能加油，很看好zimg，奈何我技术太渣，帮不了什么忙去改代码，手机码字不易，望作者考虑

**Comment by buaazp** [comment]
1. 作为一张图片，首要问题就是防盗链？你搞错了轻重缓急，防盗链不是不做，而是优先级低。
2. zimg的设计思路我写了好几篇文章，你最好先去看一看。大致思路就是，上传得先经过web server进行权限验证，然后才内网传给zimg，zimg属于企业内部私有云服务这种范畴。
3. 手机打字真不容易，但是看字容易啊，你说的这功能我早就做了好伐？

**Comment by shinebay** [comment]
谢谢，那请问如何防盗链呢？另外，你的意思是，不能客户端直传到zimg服务器，而还要经过中间web server处理后再上传至zimg?这样速度是硬伤啊

**Comment by buaazp** [comment]
1. 防盗链如何做？我还没想到好办法，依然会涉及到用户权限这个问题。

2. 速度确实是硬伤，但“内网多传输一次图片这个过程”根本不是关键问题，你要搞清楚这样做是为了什么，以及为什么不直接在zimg里做权限控制。

一旦涉及到用户权限控制，你就必须有一套用户体系，一般网站架构中，这种用户体系已经存在了，数据库存储＋web后端处理逻辑（是不是PHP写的不重要），不管一个请求是不是为了存图片，只要你想控制权限，必须得经过这么一层。只要经过这一层，速度已经慢了，因为要过一次数据库（至少是缓存，那是另一个问题，不展开了）。

现在你希望这一层放到zimg里来做，那zimg依然需要挂一个数据库，依然要写一套关于用户的逻辑，并不是说这套逻辑用C写，就能快多少，我之前的文章里提到zimg比PHP快，说的是图片的处理过程快，是因为避免了大量拷贝和IO操作；但是你见过哪个网站的用户注册和登录模块是用C来写的？要搞清楚，瓶颈是在数据库！

根据我上面的说明，既然已经知道过数据库必然会慢，那么在哪儿慢都是一样的。一次慢查询的延迟比一次内网传输（千兆网卡）高两到三个数量级，你觉得这时候有必要追究那几毫秒的时间吗？

而且，更重要的是，每个网站的用户体系都是不一样，我怎么可能在zimg里强行引入一套，而给更多已有用户系统的人找麻烦呢？

如果你没有做过大规模系统，就先不要去钻那么点性能问题的牛角尖，好做的话我肯定早就做了。By the way，为了让你信服，我可以告诉你，新浪微博的图片处理系统，也是独立于用户体系存在的，上传过程就是靠其他平台校验权限之后再传过来的，下载过程根本不做防盗链。

此类问题我已经说了好多遍，核心就在于zimg里不带用户数据，实在不想再解释了，以后此类问题直接关闭不再解答。
