### ISSUE TITLE
如何理解zimg"企业内部私有云"的概念?

### ISSUE THREAD

**Issue by shinebay** [buaazp/zimg#71]
客户端上传图片，"上传得先经过web server进行权限验证，然后才内网传给zimg"，是不是就是，假设一台独立的图片服务器，绑定域名www.abc.com，安装完zimg后，为了控制上传权限，仍然需要安装nginx和php，客户端上传一张图片到www.abc.com，先经过nginx和php处理，然后再由php curl post到本机127.0.0.1:4869传给zimg?而在读你相关文章中，都是尽量避开php的，比如php文件上传"有一次读文件一次写文件是多余的"，这么说来仍然还是需要php处理文件上传?我的理解难免让大神贻笑大方，但小白真心请教，求大神解疑释惑
另外，zimg防盗链应该如何设置?相信很多web运营人员也有相同疑惑，谢谢哈

**Comment by buaazp** [comment]
你非想要控制上传权限的话，就多用php上传一次好了。至少你在下载和裁剪缩略图的时候能省掉好多php慢操作。

不想引入这一次php上传？目前我还没有想到好办法，希望大家能想出点可行通用的好办法。

#70
