### ISSUE TITLE
请教一下如何禁用放大功能

### ISSUE THREAD

**Issue by adouggy** [buaazp/zimg#72]
如果传入参数w为一个特别大得值，会消耗很多服务器资源做差值。
我目前的应用场景并不需要获取一个比原图更大的图片，如果w或者h大于原图直接返回原图即可。
请加一下如何配置这点？（我已经翻阅了一遍文档，没有找到）

感谢作者

**Comment by buaazp** [comment]
Mark

这个可以做，回头做成一个配置项。

**Comment by buaazp** [comment]
这个功能已经实现并且合并至master分支中，配置文件中增加了相关选项：

```
--禁用图片放大
disable_zoom_up = 0
```

如需禁用放大设置此选项值为1即可，如果禁用放大之后有w或h大于原图的请求，返回原图大小。欢迎试用并反馈

**Comment by adouggy** [comment]
已安装启用，功能ok

**Comment by buaazp** [comment]
Good
