### ISSUE TITLE
zimg如何绑定域名访问了？

### ISSUE THREAD

**Issue by qswl** [buaazp/zimg#75]
安装了老半天终于成功了，现在我要想绑定到指定域名上面，该如何做，请指教？

**Comment by buaazp** [comment]
域名通过DNS设置到IP上，zimg用80端口启动。

如果80端口已被web server如nginx等占用，就在nginx里设置域名请求转发到zimg启动的端口。

**Comment by qswl** [comment]
谢谢，一时蒙了，老是想在zimg上面下手，忽略nginx这块了，已经解决

**Comment by buaazp** [comment]
Good
