### ISSUE TITLE
图片上传成功，但是读取失败

### ISSUE THREAD

**Issue by visionding** [buaazp/zimg#77]
部署环境：Cent OS 6.6下编译安装，imagemagick使用6.9.1-2，未开启memcached，图片存储使用SSDB。
问题描述：有部分文件在上传时是成功的，SSDB里面也显示的有大小，但是在读取的时候获取长度为0。相关日志如下：
2015/05/11 13:32:15:829740 [DEBUG] Start to Find the Image...
2015/05/11 13:32:15:829998 [DEBUG] Failed to execute get [fdf968e95c41d6886f77d851467a17ad:0:0:1:0:-1:-1:0:75:none] from ssdb.
2015/05/11 13:32:15:833237 [DEBUG] Succeed to get [fdf968e95c41d6886f77d851467a17ad] from ssdb. length = [490166].
2015/05/11 13:32:15:834083 [DEBUG] Webimg Read Blob Failed!
2015/05/11 13:32:15:834280 [DEBUG] get buffer length: 0
2015/05/11 13:32:15:834361 [DEBUG] Got the File!
2015/05/11 13:32:15:834418 [DEBUG] headers: 1
2015/05/11 13:32:15:834487 [INFO] 10.2.1.82 succ pic:fdf968e95c41d6886f77d851467a17ad w:0 h:0 p:1 g:0 x:-1 y:-1 r:0 q:75 f:none size:0
2015/05/11 13:32:15:834539 [DEBUG] ============get_request_cb() DONE!===============

我们在Cent OS 7上用rpm安装包部署了一个，暂时未出现这个问题。

**Comment by tllen** [comment]
imagemagick 换成低版本的试一下

**Comment by buaazp** [comment]
看log是imagemagick调用打开文件接口时返回失败，具体什么原因还不好确定，建议换个imagemagick试试。

**Comment by visionding** [comment]
在Cent OS 7上运行十几天一切正常，应该是版本的问题，我们决定就在Cent OS 7上直接安装RPM包，不再折腾了，感谢作者！
