### ISSUE TITLE
对负载均衡的支持

### ISSUE THREAD

**Issue by qgm168** [buaazp/zimg#79]
一般负载均衡转发真实IP是用http头X-Forwarded-For表示，希望能支持取IP优先取X-Forwarded-For

**Comment by buaazp** [comment]
Get the real IP address when header `X-Forwarded-For` is set.

More info is in [rfc7239](http://tools.ietf.org/html/rfc7239).

**Comment by buaazp** [comment]
Done.

**Comment by qgm168** [comment]
日志截取真实IP没问题可以实现，但IP权限控制应该取的还是代理的IP吧？

**Comment by buaazp** [comment]
有道理，这一块给漏掉了，我再看看

**Comment by buaazp** [comment]
Done
