### ISSUE TITLE
将来是否会出一个golang版本的zimg?

### ISSUE THREAD

**Issue by jaffwu** [buaazp/zimg#83]

**Comment by buaazp** [comment]
首先，做一个支持更大存储量（PB级）、工业可用（经过线上业务验证且运维工具链完善）的全新zimg一直是我的目标，这中间涉及到很多基础组件的开发和搭配工作，目前正在参与相关的工作中。

Golang用来开发http服务非常合适且高速，虽然还有一些性能抖动和基础库不全的问题，但全新zimg用golang来开发应该是可以确定的。

目前的进度是基础组件的开发阶段，包括消息队列（已完成）、分布式存储系统（正在进行）和图片处理库（golang目前已有的库跟imagemagick比起来差距太远），只有当这些基础组件都完备之后才能开始全新的zimg项目，不然都还是挂羊头卖狗肉，没有实际的变化。

基本上就是这样的规划。

**Comment by jaffwu** [comment]
我同意你的观点。从你的描述中，拖累项目进度的原因可能是缺少图片处理库。我提个建议（可能不对），就是把zimg分成两个部分（或服务），一个专注于存储服务，另一个专注于图片处理。存储服务的话，现阶段可以先开发，以后，基础组件完备，再开发图片处理。举个例子“picfit”项目可能接近这种模式。

**Comment by buaazp** [comment]
哈哈，其实我就正在按这个步骤在做呢，新zimg到时候肯定不是简单的一个程序了，而是分模块部署的大系统。另外透漏下目前正在开发的这个存储系统还是超牛X的。

**Comment by buaazp** [comment]
哈哈，其实我就正在按这个步骤在做呢，新zimg到时候肯定不是简单的一个程序了，而是分模块部署的大系统。另外透漏下目前正在开发的这个存储系统还是超牛X的。

**Comment by DTXLink** [comment]
建议出一个 分布式文件系统

**Comment by buaazp** [comment]
@DTXLink on the way
