### ISSUE TITLE
虚拟机配置IP，但内网其他机器不能访问

### ISSUE THREAD

**Issue by Mignet** [buaazp/zimg#85]
如题，我自己IP是172.25.2.18虚拟机的IP是172.25.2.20,虚拟机系统是centos7 64位。配置文件里已经将IP改为了172.25.2.20.但主机通过这个地址访问不了>_<，但虚拟机和主机IP都是可以互相ping通的。zimg成功启动没错误。虚拟机通过20的IP能正常访问到，help

**Comment by buaazp** [comment]
如果是403错误的话，log里会输出实际过来的IP地址，你看一下实际IP是啥，在不在access范围内。

另外，把你的配置文件中关于access的部分贴出来我看看。

**Comment by Mignet** [comment]
不是403，也不是404，是timeout。已经找到原因了，CentOS7的防火墙是firewall，我一直修改iptables，掉坑里了。已解决。
