### ISSUE TITLE
Can you make one for redis storage?

### ISSUE THREAD

**Issue by hwongcom** [buaazp/zimg#89]
Can you make one/connector for redis storage? please? thanks. also, deb and rpm package them... thank you very much.

**Comment by hhservice** [comment]
the zimg support Memcached(beansdb) and Redis(SSDB) protocol .

**Comment by buaazp** [comment]
set your config file like these:

```
mode            = 1
ssdb_ip         = '127.0.0.1'
ssdb_port      = 6379
```

replace the ip/port with your redis ip/port.
