### ISSUE TITLE
图片经过处理之后似乎会变大

### ISSUE THREAD

**Issue by solohac** [buaazp/zimg#92]
HI，有个疑问
上传原图为0*0，大小为29777 ，使用MagickGetImageFormat得到的原图格式为JPEG。
经过代码处理，q=100的图片大小会增大许多，信息如下：

-rw-r--r-- 1 root root 29777 Jul  1 02:37 0*0
-rw-r--r-- 1 root root 70924 Jul  1 02:41 0*0_p1_g0_-1*-1_r0_q100.jpeg
-rw-r--r-- 1 root root 70924 Jul  1 02:40 0*0_p1_g0_-1*-1_r0_q100.none

似乎如果不通过MagickSetImageCompressionQuality设置图片质量，则图片会按默认75来设置。
但是如果设置为质量100，图片会变大许多。
这其中是不是有什么问题呢？

**Comment by buaazp** [comment]
图片背im处理过之后确实会变大，原因比较多，你这个case是因为原图的quality都不到100，被设置成100其实是增强了画质，所以体积肯定会变大。

目前zimg里用的是这个方法[MagickSetImageCompressionQuality](http://www.imagemagick.org/api/magick-image.php#MagickSetImageCompressionQuality) 来设置图片质量，如果你有发现其他更加合适的方法，可以告诉我一下我来替换掉。

**Comment by buaazp** [comment]
贴一下zimg里关于quality处理的代码段：

被注释掉的那一段是之前写的，理论上比较可靠，但实际上从图片里很难能获取到准确的压缩比，所以后来干脆不用了。

```
    /* set quality */
    /*
    int quality = 100;
    int im_quality = MagickGetImageCompressionQuality(im);
    im_quality = (im_quality == 0 ? 100 : im_quality);
    LOG_PRINT(LOG_DEBUG, "wi_quality = %d", im_quality);
    quality = req->quality < im_quality ? req->quality : im_quality;
    */
    LOG_PRINT(LOG_DEBUG, "wi_set_quality(im, %d)", req->quality);
    ret = MagickSetImageCompressionQuality(im, req->quality);
    if (ret != MagickTrue) return -1;
```

**Comment by solohac** [comment]
确实是IM里面的问题，我会继续查找方法，如果找到了好的方法，我会及时反馈，谢谢

**Comment by solohac** [comment]
重新想了想，没明白为什么配置文件中要进行默认质量的配置：
--默认保存新图的质量
quality         = 100

我觉得默认质量，应该就是按原图质量来设置就可以了。
理由：
我找了一张质量为75的作为原图，设置质量为100后转换，通过ImageMagick自带的工具compare进行对比，发现其实并没有实质上的提升。
![diffwith100](https://cloud.githubusercontent.com/assets/13010947/8494685/9c4fce08-2199-11e5-8cac-e188199088dc.jpg)

所以我认为这个参数设置没有必要，如果用户请求的时候带上参数q=100，应知道q=100会可能带来图片增大的风险。

基于以上理由，我对代码逻辑进行了如下调整：
void get_request_cb(evhtp_request_t *req, void *arg) 函数：
//原逻辑，如果请求质量不为0，则按请求质量设置；否则按配置文件默认质量设置
//改为：如果请求质量不为0，则按请求质量设置；否则按原图质量设置,标识为0。直接注释掉就是这个逻辑
//quality = (quality != 0 ? quality : settings.quality);

int convert(MagickWand *im, zimg_req_t *req) 函数：
if (0 != req->quality )
	{
		LOG_PRINT(LOG_DEBUG, "wi_set_quality(im, %d)", req->quality);
		ret = MagickSetImageCompressionQuality(im, req->quality);
		if (ret != MagickTrue) 
			return -1;
	}


效果：
在默认情况下，即用户非显示传参要求修改质量的情况下，图片按原质量处理。
compare后，效果如下：
![diff1](https://cloud.githubusercontent.com/assets/13010947/8494701/dc81d8ae-2199-11e5-97b3-63bf0fc864f8.jpg)

**Comment by buaazp** [comment]
首先，我之前说过im处理图片会变大的原因很多，并不止跟quality有关，更别说你设置一个`quality=100`就指望它能输出的质量提高25%的图片了。这里面水很深，要调优的参数太多了。

默认配置是希望即使不带任何参数的请求，也可以得到压缩过的体积较小的图片（我的方法无法100%保证体积变小，你的也同样无法保证）。

你如果不嫌每次都要在参数中增加`q=75`麻烦的话，当然可以改成这样。同时，如果你就是想拿到原图，也可以用参数`p=0`来实现。

这个问题就演变成了【在都不加任何参数的情况下，想得到原图的人更多呢，还是想得到小图的人更多】，经验上，想要小图的更多。你要明白一点，绝大多数的图片经过默认设置会大幅度降低体积，这个默认配置是实践经验得出的，你应该根据自己的业务场景来调整数值。
