### ISSUE TITLE
图片显示错误的问题

### ISSUE THREAD

**Issue by snowboy8** [buaazp/zimg#94]
假如说用户上传的图片并非是真正的图片，他是可以上传的，但打开链接显示的是404错误，如何避免这类文件的上传呢，比如说可以控制mime类型。

**Comment by snowboy8** [comment]
另外CENTOS 6.5 一直无法安装，我只能采用UBUNTU来安装，有啥好的方法可以解决呢

**Comment by buaazp** [comment]
1. 无法完全避免，想检测图片只能尝试打开，如果上传的时候就做这个事情，必然导致上传时间增加，得不偿失。

2. 无法安装是怎么无法安装？报什么错误起码贴一下吧，不然怎么帮你解决。

**Comment by zzc1984** [comment]
centos 6.5可以编译安装成功，但是安装新版本的cmake ,imagemagic,libevent,libmemcache……

**Comment by buaazp** [comment]
似的，centos6自带的包都太旧了，用起来比较麻烦。
