### ISSUE TITLE
Possible to proxy zimg through nginx?

### ISSUE THREAD

**Issue by r3wt** [buaazp/zimg#95]
I am concerned about zimg presenting a ddos oppurtunity to malicious users. so i want to proxy requests to it with nginx with simple rate limiting scheme, as so. is it possible?

`nginx.conf`

```
location /zimg {
     limit_req zone=zimg burst=2;
     fastcgi_pass 127.0.0.1:4869;
}
```

**Comment by buaazp** [comment]
zimg is not a fastcgi program, so you can modify your nginx.conf like mine:

```
/etc/nginx/vhost/demo.buaa.us.conf
```

```
server
        {
                listen       80;
                server_name demo.buaa.us;
                index index.html index.htm index.php default.html default.htm default.php;
                root  /home/zippo/demo;

                include other.conf;
                location ~
                        {
                                proxy_pass http://127.0.0.1:4869;
                                proxy_set_header X-Real-IP $remote_addr;
                        }

                access_log  /home/wwwlogs/demo.buaa.us.log  demo.buaa.us;
        }
```

**Comment by r3wt** [comment]
Thanks guy!

**Comment by r3wt** [comment]
For some reason, i get this message:

http://puu.sh/joxTd/00c153c8af.png

**Comment by buaazp** [comment]
You should check the log of zimg to get the reason of 404. Or you can paste the log so I can find what happend. If zimg didn't catch the request, maybe the nginx conf should be modified.

**Comment by r3wt** [comment]
```
2015/08/04 03:28:22:171404 [INFO] 127.0.0.1 refuse url illegal
```

**Comment by buaazp** [comment]
Show me your nginx conf.

**Comment by r3wt** [comment]
I was able to figure it out with a regex. originally i tried matching the regex in the location, but when i instead try the regex inside the location, it works now.
```
location ~* ^/uploads/image/ {
	rewrite ^/uploads/image/(.*) /$1 break;
	proxy_pass http://127.0.0.1:4869;
	proxy_set_header X-Real-IP $remote_addr;
}
```

**Comment by zhoukk** [comment]
proxy_set_header X-Real-IP $remote_addr;

should be

proxy_set_header X-Forwarded-For $remote_addr;
