### ISSUE TITLE
Feature Enhancement: Change Naming schema for image storage

### ISSUE THREAD

**Issue by r3wt** [buaazp/zimg#98]
Currently, images are named with an `md5`. This presents a very serious problem with hash collisions. 

In #97 i discovered this issue first hand with following code in php which demonstrate the problem:

```php
public function update_avatar($avatar)
{
    $app = \StarterKit\App::getInstance();
    if(!empty($this->avatar)){
        //user has previously stored an avatar. delete the old one.
        $app->get_request($app->args['img_url'].'admin?md5='. $this->avatar .'&t=1');
    }
    $this->avatar = $avatar;
    $db = $app->db;
    $model = $db->model('user',$this->id);
    $db->updateColumn($model,'avatar',$this->avatar);
    return true;
}

```

As you see here, i want my application to delete the users current avatar if they have already uploaded one, it will delete the old one. 

Q: *So, what happens when they reupload the same avatar as they already have stored?*
A: **the image is deleted, since they have the same md5**

**Possible solutions hinge around changing lazy naming convention**

pseudo code: `md5( file + time )` instead of current implementation which is `md5( file )`

this way we can track permutations and have more optimal management of storage.

**Comment by buaazp** [comment]
If images have the same md5, they are SAME images.

I don't know what problem in your case. If users reupload the same avatar, you delete old one first and then post new one, they just have a same url.

Is there anything wrong?

**Comment by r3wt** [comment]
You have to post the new one first to have the md5 of the file...
